### ISSUE TITLE
[Logbook] - Add analytics tracker

### ISSUE THREAD

**Issue by devformatters** [thematters/logbook#145]
Installation tracker
- Landing
  - Claim
  - My Bookcase
  - Showcase
  - Recently written: Enter Library
  - Recently written: Content Card
  - About us links
- Library
  - Content card
  - Content card share button
- Logbook page
  - OpenSea button
  - Share button
  - Content card: creator address
  - Content card: Polygonscan

- Share Dialog
  - Each share channel button

**Comment by tx0c** [comment]
#156 has resolved partially, still need another PR
