### ISSUE TITLE
[Logbook] - Component: Search Bar

### ISSUE THREAD

**Issue by robertu7** [thematters/logbook#20]
![image](https://user-images.githubusercontent.com/4065233/153193285-30ef66b4-03f6-4575-8a70-cbf584f78cc2.png)

deps: 
- #14

Refs:
- [Searchbar](https://github.com/thematters/traveloggers-app/blob/2ddeb855e14fbd7cad8141b9a02163b9fc516697/src/views/Logbook/LogbookList/Searchbar/index.tsx)

**Comment by devformatters** [comment]
@pitb2022 
Codes related to this issue are merged, right?

**Comment by tx0c** [comment]
merged in #37 in commit bd0dbbd9
